language: node_js
before_script: cd ./client && npm install && npm run build
node_js:
- '8'
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
script:
- nohup npm run server &
deploy:
  provider: heroku
  api_key:
    secure: b09bb6ee-a366-44a0-913a-89ee1c640e02
  app: food-app-web
