language: node_js
before_script: cd ./client && npm install
node_js:
- '8'
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
deploy:
  provider: heroku
  api_key:
    secure: b09bb6ee-a366-44a0-913a-89ee1c640e02
  app: food-app-web
